### ISSUE TITLE
Allow providing a build artifact to generate PDF from (from-build option)

### ISSUE THREAD

**Issue by krillboi** [kohheepeace/mr-pdf#11]
With `docusaurus-pdf`  (https://github.com/kohheepeace/docusaurus-pdf) it is possible to provide a build artifact as generation input. I'd like to be able to provide a build artifact instead of starting a local webserver.

Is this possible with `mr-pdf`?

**Comment by kohheepeace** [comment]
@krillboi no and not planned 👍
