### ISSUE TITLE
Add multiple initialDocUrls to handle multiple doc sections

### ISSUE THREAD

**Issue by kohheepeace** [kohheepeace/mr-pdf#16]
https://github.com/kohheepeace/mr-pdf/issues/10#issuecomment-852218292

**Comment by kohheepeace** [comment]
Implemented and close

**Comment by covalentbond** [comment]
@kohheepeace the sections are still not generated in the PDF. Please reopen this issue.

Steps to reproduce:
```
npx mr-pdf --initialDocsURL="https://zowe-docs.netlify.app/stable/getting-started/overview" --contentSelector="article" --paginationSelector=".pagination-nav__item--next > a" --excludeSelectors=".announcementBar_UUUQ,nav.navbar,.docSidebarContainer_3pwe,.docMainContainer_2pgU .col.col--3,footer.footer,.docItemContainer_2szM > .margin-vert--xl > .row > .col:first-child,.pagination-nav,.docsRating,.navbar__inner,.thin-scrollbar" --coverImage="https://docusaurus.io/img/docusaurus.png" --coverTitle="Zowe Documentation" --outputPDFFilename="zowe-docs.pdf"
```

This script is suppose to generate complete PDF for https://zowe-docs.netlify.app/ website. But only generates the first section.

**Comment by kohheepeace** [comment]
@covalentbond Sorry, 

Use, `--initialDocURLs` with comma separete. Note that `initialDocURLs` not `initialDocsURL`.
.
```
--initialDocURLs="https://zowe-docs.netlify.app/stable/getting-started/overview,https://zowe-docs.netlify.app/stable/user-guide/installandconfig,https://zowe-docs.netlify.app/stable/extend/extend-zowe-overview"
```

But, in your document, there is duplicate in https://zowe-docs.netlify.app/stable/extend/extend-zowe-overview.

So, PDF generation will loop and not finish.

**Comment by covalentbond** [comment]
@kohheepeace it gives an error: `error: unknown option '--initialDocURLs'`

I'm running this scrpit for the two sections only:
```
npx mr-pdf --initialDocURLs="https://zowe-docs.netlify.app/stable/getting-started/overview,https://zowe-docs.netlify.app/stable/user-guide/installandconfig" --contentSelector="article" --paginationSelector=".pagination-nav__item--next > a" --excludeSelectors=".announcementBar_UUUQ,nav.navbar,.docSidebarContainer_3pwe,.docMainContainer_2pgU .col.col--3,footer.footer,.docItemContainer_2szM > .margin-vert--xl > .row > .col:first-child,.pagination-nav,.docsRating,.navbar__inner,.thin-scrollbar" --coverImage="https://zowe-docs.netlify.app/img/zowe-icon.png" --coverTitle="Zowe Documentation" --outputPDFFilename="zowe-docs.pdf"
```

**Comment by kohheepeace** [comment]
@covalentbond What is the log of `mr-pdf -h` ?

**Comment by covalentbond** [comment]
It says `mr-pdf: command not found`?

**Comment by covalentbond** [comment]
Just to tell you, **--initialDocsURL=** PDF is still being generated this

**Comment by kohheepeace** [comment]
@covalentbond 
```
npx mr-pdf -h
```

![2021-06-05_00h35_21](https://user-images.githubusercontent.com/29557494/120826960-ebb15b00-c595-11eb-80c3-c7ce531e5540.png)

**Comment by covalentbond** [comment]
@kohheepeace here it is:
Have you not updated the NPM package?

```
$ npx mr-pdf -h
Need to install the following packages:
  mr-pdf
Ok to proceed? (y) y
Usage: mr-pdf [options]

Options:
  --initialDocsURL <url>           set url to start generating PDF from
  --contentSelector <selector>     used to find the part of main content
  --paginationSelector <selector>  used to find next url
  --excludeSelectors <selectors>   exclude selector ex: .nav
  --cssStyle <cssString>           css style to adjust PDF output ex: body{padding-top: 0;}
  --outputPDFFilename <filename>   name of output PDF file
  --pdfMargin <margin>             set margin around PDF file
  --pdfFormat <format>             pdf format ex: A3, A4...
  --coverTitle <title>             title for PDF cover
  --coverImage <src>               image for PDF cover. *.svg file not working!
  -h, --help                       output usage information
```

**Comment by covalentbond** [comment]
@kohheepeace Note: I'm using Docusaurus V2 here.

**Comment by kohheepeace** [comment]
@covalentbond sorry I'm so stupid. I forget to publish to npm. I updated and publish new version. Could you check it again ?

**Comment by kohheepeace** [comment]
@covalentbond And if you donwload `mr-pdf` global, you don't need to donwload puppeteer everytime.

```sh
npm i -g mr-pdf
```

**Comment by covalentbond** [comment]
@kohheepeace Thank you!! It worked 🚀

- I found that `--excludeURLs` was made to require, this option can be set to optional I think.

## Feature
- For multiple docs, can we give users the option to add sub section heading. For eg as you might have seen at https://zowe-docs.netlify.app. We have different sections like: `Get Started`, `User Guide`, `Extend`, `Troubleshoot`, `Contribute` & `Reference` and to print them we provide links of these sections respectively in `--initialDocURLs=""`.
- An optional option like `--sectionHeadings="Get Started, User Guide, Extend....."` which will contain section headings seperated by commas to add section heading in TOC. It will be a great feature.

Because in TOC, there is just a text **Table of Contents** and a very long list of links..
Just before each section starts in TOC, providing sub headings will make it easy for users to read it. Something like this:

![image](https://user-images.githubusercontent.com/53327173/120862915-5d45d500-c5a7-11eb-8ec8-6aacde7e7f5f.png)

**Comment by kohheepeace** [comment]
@covalentbond glad to hear that.

> I found that --excludeURLs was made to require, this option can be set to optional I think.

Okay thanks 👍

I would like to know what is the usecase of PDF in your case. Actually I'm not a fan of PDF, I'm making this PDF tools for future backup when closing document website.

**Comment by covalentbond** [comment]
@kohheepeace Yes, I completely agree that 800 pages PDF can be too annoying to read. But some of our users still like to read PDF. For that we need to provide them this.

**Comment by kohheepeace** [comment]
> But some of our users still like to read PDF. For that we need to provide them this.

@covalentbond I understand 👍 

And I don't fully understand your feature requests. Do you mean having multiple TOC per section (at the beginning of section)?

**Comment by covalentbond** [comment]
Have a look at this PDF: https://docs.zowe.org/stable/Zowe_Documentation.pdf

We were using a diff library to create PDF for our Vuepress website. It is having section heading as well in the TOC.
Like "Getting Started", "Extend"...

I'm willing if something this could also happen.

**Comment by covalentbond** [comment]
@kohheepeace did you get it?
