### ISSUE TITLE
Details & Summary tags are not printing properly in PDF

### ISSUE THREAD

**Issue by covalentbond** [kohheepeace/mr-pdf#19]
Some markdown pages might use `<details/>` & `<summary/>` elements in the documentation like below

<details>
  <summary>Click on it</summary>
  <p>Content will be shown</p>
</details>

Code:
```
<details>
  <summary>Click on it</summary>
  <p>Content will be shown</p>
</details>
```
## Issue:
While printing the pages these content inside these details elements hide and thus could not be read as can be find on page 2 of https://zowe-docs.netlify.app/zowe-docs.pdf as shown below:
![image](https://user-images.githubusercontent.com/53327173/120864741-5371a100-c5aa-11eb-9d80-3d8db91cfe8c.png)

## What could be done:
Look for all the `<details>` elements and print them with their open state like this

![image](https://user-images.githubusercontent.com/53327173/120865219-3be6e800-c5ab-11eb-8c7d-32514d2498a5.png)

### Code Logic
While converting to HTML, you can add an **open** attribute to `<details>` tag. So that while printing. It will print with content inside the details tag as well:
```
<details open>
  <summary>Click on it</summary>
  <p>Content will be shown</p>
</details>
```

**Comment by kohheepeace** [comment]
Use regex to find `<details>` and add `open`

**Comment by covalentbond** [comment]
Probably something like this should work, not sure where to add:

```
<script>
  var detailsArray = document.getElementsByTagName("details");
  Array.from(detailsArray).forEach(addOpenAttribute);

  function addOpenAttribute(index) {
    index.open = true;
  }
</script>
```

**Comment by covalentbond** [comment]
Just need to add this before the HTML is generated! @kohheepeace can you help me?

**Comment by kohheepeace** [comment]
@covalentbond nice code. I will add after eating breakfast.
