### ISSUE TITLE
Cascading Styles are not added in the PDF generated through latest version released

### ISSUE THREAD

**Issue by covalentbond** [kohheepeace/mr-pdf#23]
After the new release the CSS styles are not getting applied on the PDF

PDF created using latest released `mr-pdf`: [docusaurus-website-generated.pdf](https://github.com/kohheepeace/mr-pdf/files/6602203/zowe-docs.pdf)

**Comment by covalentbond** [comment]
@kohheepeace can you reproduce the issue?

**Comment by covalentbond** [comment]
@kohheepeace can you reproduce the issue? I tested this with `v1.0.3`. It works fine but PDF generated with `v1.0.4` generates without CSS and cover image. Most probably causing due to this refactoring done [here](https://github.com/kohheepeace/mr-pdf/commit/f6a75bf4ffbbfaac49fe252a67fca185b35e2cd0#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351R98).

**Comment by kohheepeace** [comment]
@covalentbond Thanks for your report and sorry! I fixed it.

**Comment by covalentbond** [comment]
Thanks for the fix :)
