### ISSUE TITLE
error of `env: node\r: No such file or directory`

### ISSUE THREAD

**Issue by genshen** [kohheepeace/mr-pdf#27]
Open an issue again.  
I installed `mr-pdf`(v1.0.5) for my mac via yarn tool.  
When I run mr-pdf, it gives me an error of `env: node\r: No such file or directory`.  
I just open the  `mr-pdf` script and fount it is `doc` format (with end line `\r\n`), not `unix` format.  
I have to convert it to unix format via vim: `:set fileformat=unix`, which could not be an easy problem if user don't  know the file format.  

---
node version: v14.15.5

**Comment by kohheepeace** [comment]
@genshen really thanks for your report. Could you check it works at `v 1.0.6` ?

**Comment by genshen** [comment]
I reinstalled v1.0.6, but it is still dos format.  
<img width="484" alt="image" src="https://user-images.githubusercontent.com/11265498/125876896-dfb6064e-fd46-461c-8720-6ad3a1acea27.png">
But source code in GitHub repo(tag v1.0.6) is unix format (which is guaranteed by Git itself).  It there anything wrong when you publishing the package?
