### ISSUE TITLE
TOC

### ISSUE THREAD

**Issue by Swader** [kohheepeace/mr-pdf#3]
The only thing missing from this awesome tool is the ability to generate a ToC to put at the top of the document, or after an intro page / cover. That way people could jump to pages and see what's where. This cannot be done on the CSS side since the pages are merged on the mr-pdf side and we have no way of knowing where each page will end up so no way to tell which anchor links to use. Additionally, the titles aren't anchored, so this would have to be done on the mr-pdf side.

**Comment by KohheePeace** [comment]
For future ref: https://github.com/simologos/papersaurus

**Comment by kohheepeace** [comment]
Implemented and close.
