### ISSUE TITLE
Page numbers

### ISSUE THREAD

**Issue by Swader** [kohheepeace/mr-pdf#4]
An option to put page numbers at the bottom (left, middle, or right within margins) of pages would be great, especially if we want to have a working TOC (#3).

**Comment by kohheepeace** [comment]
Super easy 
Ref: https://github.com/puppeteer/puppeteer/issues/5345

**Comment by covalentbond** [comment]
@kohheepeace can I work on this?

I suppose will just need to add a footerTemplate variable in [#L171](https://github.com/kohheepeace/mr-pdf/blob/master/src/utils.ts#L171)
```
footerTemplate: `
    <div style="border-top: solid 1px #bbb; width: 100%; font-size: 9px;
        padding: 5px 5px 0; color: #bbb; position: relative;">
        <div style="position: absolute; left: 5px; top: 5px;"><span class="date"></span></div>
        <div style="position: absolute; right: 5px; top: 5px;"><span class="pageNumber"></span>/<span class="totalPages"></span></div>
    </div>
  `,
```

**Comment by covalentbond** [comment]
Also a contributing guide would help a lot understanding how to test this NPM package locally!
