### ISSUE TITLE
error: unknown option '--initialDocsURL'

### ISSUE THREAD

**Issue by ar-to** [kohheepeace/mr-pdf#43]
First got this [error](https://github.com/kohheepeace/mr-pdf/issues/25)

Then upgraded to node v14.18.3 and again got this

```
npx mr-pdf --initialDocsURL="https://docusaurus.io/docs/en/installation" --paginationSelector=".docs-prevnext > a.docs-next" --excludeSelectors=".fixedHeaderContainer,footer.nav-footer,#docsNav,nav.onPageNav,a.edit-page-link,div.docs-prevnext" --cssStyle=".navPusher {padding-top: 0;}" --pdfMargin="20"
Downloading Chromium r722234 - 116.4 Mb [====================] 100% 0.0s 
error: unknown option '--initialDocsURL'
```

Any ideas?

**Comment by lvndry** [comment]
The option is named `--initalDocURLs`

**Comment by ar-to** [comment]
thanks @lvndry good catch. This issue should close with merging of https://github.com/kohheepeace/mr-pdf/pull/42

**Comment by kohheepeace** [comment]
Close for merging https://github.com/kohheepeace/mr-pdf/pull/42
