### ISSUE TITLE
Exclude list

### ISSUE THREAD

**Issue by Swader** [kohheepeace/mr-pdf#5]
Some sites have pages that are temporary, transient, or just don't translate well to printed form (lots of links of videos, or interactive graphs). Being able to provide an `--exclude-urls` option with a file that lists all URLs to be excluded, or just a full list e.g. `--exclude-urls="foo,bar,foo.*"` would be great. Notice the regex in the last one.

**Comment by kohheepeace** [comment]
implemented and close
