### ISSUE TITLE
How to get this to work with Docusaurus v2.0.0-beta.18

### ISSUE THREAD

**Issue by MickMonaghan** [kohheepeace/mr-pdf#50]
I'm running this command:
`npx mr-pdf --initialDocURLs="http:/localhost:3000/explore" --contentSelector="article" --paginationSelector=".pagination-nav__item--next > a" `
The result is an (almost) empty PDF. First page is blank, second page has the 'Table of contents' title and nothing else.
The values for the params look correct to me.
Pointers appreciated.
Quite possibly related to #31

**Comment by jafin** [comment]
I use this cmd on a beta18 site, it appears to work fine here.

`--contentSelector="article" --paginationSelector=".pagination-nav__item--next > a" --excludeSelectors=".margin-vert--xl a,[class^='tocCollapsible'],.breadcrumbs"`

**Comment by MickMonaghan** [comment]
Thanks @jafin. No, don't have a public URL unfortunately. 
Looking at the console output, it seems that it's only retrieving the initial URL, and not finding/following any of the 'Next' links. I tried with https://docusaurus.io/docs/ - (v2.0.0-beta.18 also afaict) and it works fine. 
I don't work docusaurus much. - I'll ask our docs guy see if he can pinpoint the issue - see if he has configured it in such a way that would break the default mr-pdf behaviour.

**Comment by MickMonaghan** [comment]
Yep - spoke with my docs guy... my bad, I was just running the dev server locally. I needed to run `yarn build && yarn serve` instead.
Thanks.
