### ISSUE TITLE
Lazy loading images are not included in the PDF

### ISSUE THREAD

**Issue by meddbase-steve** [kohheepeace/mr-pdf#53]
Docusaurus v2 seems to make images lazy loading by default. They are not included in the PDF because puppeteer never loads them.

Suggested approach that I've tested on my fork is to use `puppeteer-autoscroll-down` to scroll to the bottom of each page. This forces loading of all the images. I will create a PR, but welcome comments.

**Comment by kohheepeace** [comment]
@meddbase-steve After merging PR #54, do you feel stuck on the last page ? Though, I'm not sure this is related with PR #54

**Comment by meddbase-steve** [comment]
Hi, I'll give it a test now.

**Comment by meddbase-steve** [comment]
For my docusaurus v2 site, the latest version of mr-pdf (run with npx) completes successfully and includes my footers and images. Generating the pdf is a bit slower when encoding actual images, could that be what you're seeing?

**Comment by kohheepeace** [comment]
@meddbase-steve Okay, It seemed a bit stuck when generating the PDF **on the last page**, but it may be due to a different PR. 

Anyway, thanks for your work 👍 I close this issue.
