### ISSUE TITLE
[bug] only capture part of content for Docusaurus 2.0.0-rc1

### ISSUE THREAD

**Issue by JalinWang** [kohheepeace/mr-pdf#61]
Test command:
```
npx mr-pdf --initialDocURLs="https://docusaurus.io/docs" --contentSelector="article" --paginationSelector=".pagination-nav__item--next > a" --excludeSelectors=".margin-vert--xl a,[class^='tocCollapsible'],.breadcrumbs"
```

Screenshot
![image](https://user-images.githubusercontent.com/20621784/183283981-f450d087-c259-4ad1-8aa5-570ae987a4a6.png)

**Comment by heywalter** [comment]
I've got the same issue, is there another way to solve the problem? Thanks.

**Comment by heywalter** [comment]
@JalinWang  Finally, I've figured out the solution(Docusaurus v2.2). Maybe you should try the command below.

`npx mr-pdf --initialDocURLs="your domain" --contentSelector="article" --paginationSelector=".pagination-nav__link--next" --excludeSelectors=".margin-vert--xl a"  --coverTitle="Docusaurus v2"`

btw, remember to replace the domain, good luck.

**Comment by kohheepeace** [comment]
Close the issue according to the @heywalter comment solution. Thanks!
