### ISSUE TITLE
no effect？

### ISSUE THREAD

**Issue by chaofanx** [kohheepeace/mr-pdf#68]
first, i use this command  to install it:
```bash
sudo npm i -g mr-pdf
```

then, i execute this command:
```bash
mr-pdf --initialDocURLs="http://localhost:3000/docs/intro" --contentSelector="article" --paginationSelector="pagination-nav__link--next" --excludeSelectors=".theme-doc-breadcrumbs,a.theme-edit-this-page" --coverImage="https://docusaurus.io/img/docusaurus.png" --coverTitle="Docusaurus v2"
```

But after a few seconds, the command returns directly without any information or errors

> **docusaurus** version is `2.4.0`

I am sure this doc url is valid and accessible and this folder is writable and readable

In fact I also tried it with `npx mr-pdf xxxx` and got the same response

My node version is `v18.15.0` and npm version is `9.5.0`

**Comment by jean-humann** [comment]
I have created a new repo and merged all usefull PRs [here](https://github.com/jean-humann/docs-to-pdf), feel free to contribute
