### ISSUE TITLE
Only works on Windows?

### ISSUE THREAD

**Issue by paulhh** [KohheePeace/mr-pdf#8]
Hi,

I can get great results on Wiindows, but if I try and run npx mr-pdf on Mac it gives the following error:

npm ERR! path /Users/xxx/.npm/_npx/69077/lib/node_modules/mr-pdf/bin\index.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/xxx/.npm/_npx/69077/lib/node_modules/mr-pdf/bin\index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2020-10-08T08_28_56_179Z-debug.log
Install for mr-pdf@latest failed with code 254

I assume because the path has a \ not /

Would be good if it could work on Mac/linux!

Thanks for the great software.

Paul.

**Comment by KohheePeace** [comment]
@paulhh thanks for your report. This is a bug.

**Comment by KohheePeace** [comment]
close for no reply and confirmed that it worked in mac environment.
